In [1]:
import pandas as pd
import numpy as np

In [3]:
countries = pd.read_csv(r"C:\Users\KondasaniBalaji\ai_training\Week1\Day5\Countries.csv")
countries.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [7]:
# country with  highest population
countries[countries["population"]==countries["population"].max()][["country","population"]]

   country  population
75   India  1417173173

In [9]:
# capital of country with highest population
countries[countries["population"]==countries["population"].max()][["country","capital_city","population"]]

   country capital_city  population
75   India    New Delhi  1417173173

In [11]:
# country with least population
countries[countries["population"]==countries["population"].min()][["country","population"]]

    country  population
179  Tuvalu       11312

In [13]:
countries[countries["population"]==countries["population"].min()][["country","capital_city","population"]]

    country capital_city  population
179  Tuvalu     Funafuti       11312

In [19]:
# top d countries with highest democratic score
countries.sort_values(by="democracy_score",ascending=False).head(4)[["country","capital_city","democracy_score"]]

         country capital_city  democracy_score
127       Norway         Oslo             9.87
74       Iceland    Reykjavík             9.58
164       Sweden    Stockholm             9.39
122  New Zealand   Wellington             9.26

In [32]:
# get total regions
countries["region"].value_counts().count()

np.int64(22)

In [83]:
# countries in eastern europe region
countries[ countries["region"] == "Eastern Europe"][["country","population"]].sort_values(by="population",ascending=False)

             country  population
140           Russia   143555736
181          Ukraine    38000000
136           Poland    37561599
139          Romania    18956666
43    Czech Republic    10526073
73           Hungary     9683505
14           Belarus     9208701
24          Bulgaria     6465097
151  Slovak Republic     5431752
111          Moldova     2592477

In [92]:
#political leader of second highest populated country
countries.nlargest(n=2,columns="population")[["political_leader","country"]].iloc[1]

political_leader    Xi Jinping
country                  China
Name: 34, dtype: str

In [97]:
# countries whose political leaders are unknown
countries[countries["political_leader"].isna()][["country","political_leader"]]

                            country political_leader
27                       Cabo Verde              NaN
151                 Slovak Republic              NaN
159             St. Kitts and Nevis              NaN
160                       St. Lucia              NaN
161  St. Vincent and the Grenadines              NaN
172                     Timor-Leste              NaN
190              West Bank and Gaza              NaN

In [99]:
# how many countries have republic in their full name
countries[countries["country"].str.contains("Republic")][["country","political_leader"]]

                      country           political_leader
31   Central African Republic  Faustin-Archange Touadéra
43             Czech Republic               Andrej Babiš
49         Dominican Republic              Danilo Medina
90            Kyrgyz Republic  Mukhammedkalyi Abylgaziev
151           Slovak Republic                        NaN
166      Syrian Arab Republic            Bashar al-Assad

In [108]:
countries[ countries["region"].str.contains("Africa") ][["country","region","population"] ].nlargest(n=2,columns="population").iloc[1]

country             Ethiopia
region        Eastern Africa
population         123379924
Name: 57, dtype: object