In [6]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kondasanibalaji\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\kondasanibalaji\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB 660.6 kB/s eta 0:00:15
    --------------------------------------- 0.2/9.9 MB 2.4 MB/s eta 0:00:05
   - -------------------------------------- 0.3/9.9 MB 2.5 MB/s eta 0:00:04
   - -------------------------------------- 0.5/9.9 MB 2.6 MB/s eta 0:00:04
   -- ------------------------------------- 0.5/9.9 MB 2.6 MB/s eta 0:00:04
   -- ------------------------------------- 0.6/9.9 MB 2.5 MB/s eta 0:00:04
   --- ------------------------------------ 0.8/9.9 MB 2.5 MB/s eta 0:00:04
   --- ------------------------------------ 0.9/9.9 MB 2.5 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/9.9 MB 2.5 MB/s eta 0:00:04
   ---- ----------------------------------- 1.1/9.9 MB 2.6 MB/s eta 0:00:04
   ---- ----------------------------------- 1.2/9.9 MB 2.4 MB/s eta 0:00:04
   ----- ---------------------------------- 1.3/9.9 MB 2.5 MB/s eta 0:00:04
   ----- ---------------------------------- 1.5/9.9 MB 2.5 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.9 MB 2.5 MB/s eta 0:00:04
   ------ --------------------------------- 1.7/9.9 MB 2.5 MB/s eta 0:00:04
   ------- -------------------------------- 1.8/9.9 MB 2.5 MB/s eta 0:00:04
   ------- -------------------------------- 1.9/9.9 MB 2.5 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.9 MB 2.5 MB/s eta 0:00:04
   -------- ------------------------------- 2.2/9.9 MB 2.5 MB/s eta 0:00:04
   --------- ------------------------------ 2.2/9.9 MB 2.5 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/9.9 MB 2.5 MB/s eta 0:00:03
   ---------- ----------------------------- 2.5/9.9 MB 2.5 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.9 MB 2.5 MB/s eta 0:00:03
   ---------- ----------------------------- 2.7/9.9 MB 2.5 MB/s eta 0:00:03
   ----------- ---------------------------- 2.8/9.9 MB 2.5 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.9 MB 2.5 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.9 MB 2.5 MB/s eta 0:00:03
   ------------ --------------------------- 3.2/9.9 MB 2.5 MB/s eta 0:00:03
   ------------- -------------------------- 3.3/9.9 MB 2.5 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/9.9 MB 2.5 MB/s eta 0:00:03
   -------------- ------------------------- 3.6/9.9 MB 2.5 MB/s eta 0:00:03
   -------------- ------------------------- 3.7/9.9 MB 2.5 MB/s eta 0:00:03
   --------------- ------------------------ 3.8/9.9 MB 2.5 MB/s eta 0:00:03
   --------------- ------------------------ 3.9/9.9 MB 2.5 MB/s eta 0:00:03
   ---------------- ----------------------- 4.0/9.9 MB 2.5 MB/s eta 0:00:03
   ---------------- ----------------------- 4.1/9.9 MB 2.5 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.9 MB 2.5 MB/s eta 0:00:03
   ----------------- ---------------------- 4.3/9.9 MB 2.5 MB/s eta 0:00:03
   ----------------- ---------------------- 4.4/9.9 MB 2.5 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.9 MB 2.5 MB/s eta 0:00:03
   ------------------ --------------------- 4.6/9.9 MB 2.5 MB/s eta 0:00:03
   ------------------ --------------------- 4.7/9.9 MB 2.4 MB/s eta 0:00:03
   ------------------- -------------------- 4.8/9.9 MB 2.5 MB/s eta 0:00:03
   ------------------- -------------------- 4.9/9.9 MB 2.4 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.9 MB 2.4 MB/s eta 0:00:03
   -------------------- ------------------- 5.1/9.9 MB 2.4 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 2.4 MB/s eta 0:00:02
   --------------------- ------------------ 5.3/9.9 MB 2.4 MB/s eta 0:00:02
   --------------------- ------------------ 5.3/9.9 MB 2.4 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 2.4 MB/s eta 0:00:02
   ---------------------- ----------------- 5.6/9.9 MB 2.4 MB/s eta 0:00:02
   ---------------------- ----------------- 5.7/9.9 MB 2.4 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.9 MB 2.4 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.9 MB 2.4 MB/s eta 0:00:02
   ----------------------- ---------------- 5.9/9.9 MB 2.4 MB/s eta 0:00:02
   ------------------------ --------------- 6.1/9.9 MB 2.4 MB/s eta 0:00:02
   ------------------------ --------------- 6.2/9.9 MB 2.4 MB/s eta 0:00:02
   ------------------------- -------------- 6.2/9.9 MB 2.4 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 2.4 MB/s eta 0:00:02
   ------------------------- -------------- 6.4/9.9 MB 2.3 MB/s eta 0:00:02
   -------------------------- ------------- 6.5/9.9 MB 2.3 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.9 MB 2.3 MB/s eta 0:00:02
   --------------------------- ------------ 6.7/9.9 MB 2.3 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 2.3 MB/s eta 0:00:02
   --------------------------- ------------ 6.9/9.9 MB 2.3 MB/s eta 0:00:02
   ---------------------------- ----------- 7.0/9.9 MB 2.3 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.9 MB 2.3 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.9 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 7.2/9.9 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.9 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 7.4/9.9 MB 2.3 MB/s eta 0:00:02
   ------------------------------ --------- 7.5/9.9 MB 2.3 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.9 MB 2.3 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.9 MB 2.3 MB/s eta 0:00:01
   ------------------------------- -------- 7.7/9.9 MB 2.3 MB/s eta 0:00:01
   ------------------------------- -------- 7.8/9.9 MB 2.3 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.9 MB 2.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.0/9.9 MB 2.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 2.3 MB/s eta 0:00:01
   --------------------------------- ------ 8.2/9.9 MB 2.3 MB/s eta 0:00:01
   --------------------------------- ------ 8.3/9.9 MB 2.3 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.9 MB 2.3 MB/s eta 0:00:01
   ---------------------------------- ----- 8.5/9.9 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.8/9.9 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.0/9.9 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.1/9.9 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 9.3/9.9 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 9.5/9.9 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 9.6/9.9 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  9.8/9.9 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  9.8/9.9 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 2.2 MB/s eta 0:00:00
Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl (12.6 MB)
Downloading tzdata-2026.1-py2.py3-none-any.whl (348 kB)
   ---------------------------------------- 0.0/349.0 kB ? eta -:--:--
   -------------- ------------------------- 122.9/349.0 kB 3.6 MB/s eta 0:00:01
   ----------------------------- ---------- 256.0/349.0 kB 3.2 MB/s eta 0:00:01
   -------------------------------- ------- 286.7/349.0 kB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 349.0/349.0 kB 2.4 MB/s eta 0:00:00
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2 tzdata-2026.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\KondasaniBalaji\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)

3.0.2

USE CASE OF PANDAS

1. Data Cleaning
2. Data Analysis
3. Data Transformation
4. Data Visualization
5. Data Aggregation
6. File Handling
7. Data Filtering and Selection
8. Time Series Analysis

SERIES
    1. Stacking of data -- vertically
    2. axis or index are called labels
    3. 1d array capable of holding any kind of data
    4. Data can be a list , np.array and dictionary
    
    A Series has three main parts:
        1. index
        2. values
        3. name - column

In [7]:
labels = ["a","b","c"]
my_list = [1,2,3]
data = np.array([4,5,6])
values = {"a":1,"b":2,"c":3}

print(pd.Series(data,labels))
pd.Series(my_list,labels)

a    4
b    5
c    6
dtype: int64

a    1
b    2
c    3
dtype: int64

DATAFRAMES

    1. Multiple Series stacked horizontally with labels.
    2. Can be created from list of lists , dictionary

In [11]:
# creating a dataframe
data = {
    "Name":["a","b","c","d"],
    "Age":[20,21,22,23],
    "City":["vzy","hyd","mumbai","bangalore"],
    "Salary":[20000,10000,15000,60000]
}

data2 = [
    ["a",20,"vzy",20000],
    ["b",21,"hyd",10000],
    ["c",22,"mumbai",15000],
    ["d",23,"bangalore",60000]
]

columns = ["Name","Age","City","Salary"]  

df2 = pd.DataFrame(data2,columns=columns)
print(df2)

  Name  Age       City  Salary
0    a   20        vzy   20000
1    b   21        hyd   10000
2    c   22     mumbai   15000
3    d   23  bangalore   60000

In [47]:
# Selecting and Indexing of columns

# Selecting a column -- df["column_name"] --> selects a series\
print(df2["City"],end="\n\n")

# Selecting multiple columns -- df[["column_1","column_2"]]
print(df2[["Name","City"]])

df2.iloc[[0,2,3],[0,1]]

0          vzy
1          hyd
2       mumbai
3    bangalore
Name: City, dtype: str

  Name       City
0    a        vzy
1    b        hyd
2    c     mumbai
3    d  bangalore

  Name  Age
0    a   20
2    c   22
3    d   23

In [23]:
# label based indexing -- df.loc[row, column] -- fancy indexing

print(df2.loc[0:,["Name","City"]])

  Name
0    a
1    b
2    c
3    d

LOC SELECTION PATTERNS

![alt text](image-1.png)

In [48]:
df2.loc[0:3,"Name":"Age"]

  Name  Age
0    a   20
1    b   21
2    c   22
3    d   23

In [25]:
# position based indexing -- df.iloc[row,column]

print(df2.iloc[0:3,0:3])

  Name  Age    City
0    a   20     vzy
1    b   21     hyd
2    c   22  mumbai

ILOC SELECTION PATTERNS

![alt text](image.png)

In [42]:
# Adding a column
df2["designation"]=["doctor","engineer","scientist","police"]
df2

  Name  Age       City  Salary designation
0    a   20        vzy   20000      doctor
1    b   21        hyd   10000    engineer
2    c   22     mumbai   15000   scientist
3    d   23  bangalore   60000      police

In [43]:
# deleting a column
df2.drop("designation",axis=1)
df2

  Name  Age       City  Salary designation
0    a   20        vzy   20000      doctor
1    b   21        hyd   10000    engineer
2    c   22     mumbai   15000   scientist
3    d   23  bangalore   60000      police

In [51]:
# conditional selection
df2[df2["Age"]>20]

#multiple conditions
print(df2[(df2["Age"]>20) & (df2["City"]=="bangalore")])

  Name  Age       City  Salary designation
3    d   23  bangalore   60000      police

FINDING MISSING DATA

In [66]:
data = {
    "A": [1, 2, np.nan, 4, 5],
    "B": [6, 2, 3, 4, 5],
    "C": [1, 2, 3, np.nan, np.nan],
    "D": [2, np.nan, np.nan, np.nan, 5]
}

df3 = pd.DataFrame(data)
df3

     A  B    C    D
0  1.0  6  1.0  2.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [102]:
# finding missing data -- isna() -- column wise check
print(df3.isna().sum(),end="\n\n")

# checking if null values exist
print(df3.isna().any())

A    1
B    0
C    2
D    3
dtype: int64

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
# removing missing data -- dropna() -- row wise removal , for inplace modification use inplace = True

df3.dropna()

# thresh parameter -- removes rows that dont have thresh no of non null values
df3.dropna(thresh=3)

     A  B    C    D
0  1.0  6  1.0  2.0

In [77]:
#filling missing values -- fillna()

df3.fillna(0)

# filling column with specific values

values = {"A":0,"B":3,"C":9,"D":10}
df3.fillna(value=values)

# filling column values with mean

df3.fillna(df3.mean())

     A  B    C    D
0  1.0  6  1.0  2.0
1  2.0  2  2.0  3.5
2  3.0  3  3.0  3.5
3  4.0  4  2.0  3.5
4  5.0  5  2.0  5.0

MERGING , JOINING AND CONCATENATION

In [79]:
employees = {
    "employee_id": [1, 2, 3, 4, 5],
    "name": ["John", "Anna", "Peter", "Linda", "Bob"],
    "department": ["HR", "IT", "Finance", "IT", "HR"]
}
salaries = {
    "employee_id": [1, 2, 3, 6, 7],
    "salary": [60000, 80000, 65000, 70000, 90000],
    "bonus": [5000, 10000, 7000, 8000, 12000]
}
df4 = pd.DataFrame(employees)
df6 = pd.DataFrame(salaries)

print(df4,"\n\n",df6)

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

    employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [82]:
# merging two dataframes
pd.merge(df4,df6,on="employee_id",how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [84]:
f7 = {
    "A": ["A0", "A1", "A2"],
    "B": ["B0", "B1", "B2"],
    "C": ["C0", "C1", "C2"]
}

f8 = {
    "A": ["A3", "A4", "A5"],
    "B": ["B3", "B4", "B5"],
    "C": ["C3", "C4", "C5"]
}

df7 = pd.DataFrame(f7)
df8 = pd.DataFrame(f8)

print(df7,"\n\n",df8)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

     A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [86]:
#concatenating two dataframes -- 1 arg -- list of data values to e merged

pd.concat([df7,df8],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [92]:
f9 = {
    "name": ["Alice", "Bob", "Charlie"]
}
index1 = [1, 2, 3]

f10 = {
    "score": [85, 90, 75]
}
index2 = [2, 3, 4]

df9 = pd.DataFrame(f9,index1)
df10 = pd.DataFrame(f10,index2)

In [94]:
# joining two dataframes

df9.join(df10,how="outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

GROUP BY AND AGGREGATION

In [97]:
data = {
    "Category": ["A", "B", "A", "B", "A", "B", "A", "B"],
    "Store": ["S1", "S1", "S2", "S2", "S1", "S2", "S2", "S1"],
    "Sales": [100, 200, 150, 250, 120, 180, 200, 300],
    "Quantity": [10, 15, 12, 18, 8, 20, 15, 25],
    "Date": pd.date_range("2023-01-01", periods=8)
}

df11=pd.DataFrame(data)
print(df11)

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [101]:
# group by category and calculate sum of sales

print(df11.groupby("Category")["Sales"].sum())

# group by category and calculate sum of sales

df11.groupby("Store")["Sales"].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [105]:
# group by multiple columns and perform aggregation

gd=df11.groupby(["Category","Store"])["Sales"].mean()
df11["Sales"].mean()

Category  Store
A         S1       110.0
          S2       175.0
B         S1       250.0
          S2       215.0
Name: Sales, dtype: float64

In [107]:
# .agg() combines multiple statistical operations
df11["Sales"].agg(["mean","median","mean","min","max","count","std"])

mean      187.500000
median    190.000000
mean      187.500000
min       100.000000
max       300.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64

In [113]:
#pivot tables
data = {
    "Date": pd.date_range("2023-01-01", periods=20),
    "Product": ["A", "B", "C", "D"] * 5,
    "Region": ["North", "South", "East", "West", "North", "South", "East", "West", "North", "South", "East", "West", "North", "South", "East", "West", "North", "South", "East", "West"],
    "Sales": np.random.randint(100, 1000, 20),
    "Units": np.random.randint(10, 100, 20),
    "Rep": ["John", "Mary", "Bob", "Alice", "John", "Mary", "Bob", "Alice", "John", "Mary", "Bob", "Alice", "John", "Mary", "Bob", "Alice", "John", "Mary", "Bob", "Alice"]
}

df = pd.DataFrame(data)

df["Month"] = df["Date"].dt.month_name()
df["Quarter"] = "Q" + df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A  North    638     78   John  January      Q1
1  2023-01-02       B  South    786     87   Mary  January      Q1
2  2023-01-03       C   East    676     69    Bob  January      Q1
3  2023-01-04       D   West    339     88  Alice  January      Q1
4  2023-01-05       A  North    375     59   John  January      Q1
5  2023-01-06       B  South    817     28   Mary  January      Q1
6  2023-01-07       C   East    153     45    Bob  January      Q1
7  2023-01-08       D   West    361     67  Alice  January      Q1
8  2023-01-09       A  North    199     93   John  January      Q1
9  2023-01-10       B  South    703     15   Mary  January      Q1
10 2023-01-11       C   East    403     52    Bob  January      Q1
11 2023-01-12       D   West    755     56  Alice  January      Q1
12 2023-01-13       A  North    290     74   John  January      Q1
13 2023-01-14       B  South    599     38   Mary  January      Q1
14 2023-01-15       C   East    782     52    Bob  January      Q1
15 2023-01-16       D   West    345     22  Alice  January      Q1
16 2023-01-17       A  North    962     12   John  January      Q1
17 2023-01-18       B  South    243     81   Mary  January      Q1
18 2023-01-19       C   East    102     81    Bob  January      Q1
19 2023-01-20       D   West    791     11  Alice  January      Q1

In [116]:
#values -- column in which aggregation is being applied
#index -- rows labelling or naming
#columns -- columns labelling or naming

pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc="median")

#pivot table on multiple columns

pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product")

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East       NaN    NaN  423.2    NaN   NaN   NaN  59.8   NaN
North    492.8    NaN    NaN    NaN  63.2   NaN   NaN   NaN
South      NaN  629.6    NaN    NaN   NaN  49.8   NaN   NaN
West       NaN    NaN    NaN  518.2   NaN   NaN   NaN  48.8

CROSSTABS
  counts are used by default instead of aggregations

In [117]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     0  0  5  0
North    5  0  0  0
South    0  5  0  0
West     0  0  0  5

OPERATIONS

In [123]:
indexes=["a","b","c","d","e"]
df1 = pd.DataFrame({
    "A":[1,2,3,4,5],
    "B":[10,20,30,40,50],
    "C":[100,200,300,400,500]
},index=indexes)

In [124]:
df1

   A   B    C
a  1  10  100
b  2  20  200
c  3  30  300
d  4  40  400
e  5  50  500

In [128]:
# shape , columns , info and describe
print(df1.shape)
print(df1.columns,end="\n\n")
print(df1.info(),end="\n\n")
print(df1.describe())

(5, 3)
Index(['A', 'B', 'C'], dtype='str')

<class 'pandas.DataFrame'>
Index: 5 entries, a to e
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 160.0+ bytes
None

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [129]:
#broadcasting of a column

df1["A"]+10

a    11
b    12
c    13
d    14
e    15
Name: A, dtype: int64

In [ ]:
# DATAFRAMES APPLYING SOME FUNCTIONS

df1["D"]=df1["B"].apply(lambda x :x**2)
df1

   A   B    C     D
a  1  10  100   100
b  2  20  200   400
c  3  30  300   900
d  4  40  400  1600
e  5  50  500  2500